---
# Verify this with: http://lint.travis-ci.org/
language: ruby
# Delete dependency locks for matrix builds.
before_install: rm Gemfile.lock || true
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.1.6
  - 2.3.3
  - 2.4.0
env:
  - PUPPET_VERSION="~> 3.8.7"
  - PUPPET_VERSION="~> 4.8.0"
  - PUPPET_VERSION=">= 0"
matrix:
  exclude:
    - env: PUPPET_VERSION="~> 3.8.7"
      rvm: 2.2.6
    - env: PUPPET_VERSION="~> 3.8.7"
      rvm: 2.3.3
    - env: PUPPET_VERSION="~> 3.8.7"
      rvm: 2.4.0
  allow_failures:
    - env: PUPPET_VERSION=">= 0"
# Only notify for failed builds.
notifications:
  email:
    on_success: never
sudo: false
