name          'gdsoperations-auditd'
version       '0.1.0'
source        'https://github.com/gds-operations/puppet-auditd'
author        'Government Digital Service'
license       'MIT'
summary       'Manage auditd for Ubuntu'
project_page  'https://github.com/gds-operations/puppet-auditd'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/concat'
