HOSTS:
  ubuntu-server-1204-x64:
    roles:
      - master
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    hypervisor: vagrant
  ubuntu-server-1404-x64:
    roles:
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant

